<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="27" passed="27">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="2323" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:49Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="2323" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:49Z">
      <class name="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest">
        <test-method status="PASS" signature="beforeTestCase()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="beforeTestCase" is-config="true" duration-ms="664" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:48Z">
        </test-method>
        <test-method status="PASS" signature="testSendAuthRequestWithInvalidCredentialsShouldFail()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="testSendAuthRequestWithInvalidCredentialsShouldFail" duration-ms="483" started-at="2017-03-21T19:33:48Z" finished-at="2017-03-21T19:33:48Z">
        </test-method>
        <test-method status="PASS" signature="testSendAuthRequestWithValidCredentialsShouldBeSuccessful()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="testSendAuthRequestWithValidCredentialsShouldBeSuccessful" duration-ms="6" started-at="2017-03-21T19:33:48Z" finished-at="2017-03-21T19:33:48Z">
        </test-method>
        <test-method status="PASS" signature="testSendRegistrationRequestShouldBeSuccessful()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="testSendRegistrationRequestShouldBeSuccessful" duration-ms="814" started-at="2017-03-21T19:33:48Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testSendRegistrationRequestWithBadResponseShouldFail()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="testSendRegistrationRequestWithBadResponseShouldFail" duration-ms="7" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testSendRegistrationRequestWithValidationErrorResponseShouldFail()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="testSendRegistrationRequestWithValidationErrorResponseShouldFail" duration-ms="7" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="afterTest()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceIntegrationTest@7f7d58]" name="afterTest" is-config="true" duration-ms="10" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
      </class>
      <class name="org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="2" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testAuthUserShouldFailIfConnectionErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testAuthUserShouldFailIfConnectionErrorOccurred" duration-ms="14" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException">
            <message>
              <![CDATA[Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException: Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getAuthResult(PoulpeAuthService.java:138)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.authenticate(PoulpeAuthService.java:96)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testAuthUserShouldFailIfConnectionErrorOccurred(PoulpeAuthServiceTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="1" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testAuthUserWithCorrectCredentialsShouldBeSuccessful()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testAuthUserWithCorrectCredentialsShouldBeSuccessful" duration-ms="72" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testAuthUserWithInvalidCredentialsShouldFail()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testAuthUserWithInvalidCredentialsShouldFail" duration-ms="1" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testRegisterUserShouldFailIfConnectionErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testRegisterUserShouldFailIfConnectionErrorOccurred" duration-ms="2" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException">
            <message>
              <![CDATA[Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException: Request Timeout (408) - The client did not produce a request within the time that the server was prepared to wait
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getRegistrationResult(PoulpeAuthService.java:176)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.registerUser(PoulpeAuthService.java:80)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfConnectionErrorOccurred(PoulpeAuthServiceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="1" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testRegisterUserShouldFailIfInternalServerErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testRegisterUserShouldFailIfInternalServerErrorOccurred" duration-ms="0" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException">
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.getRegistrationResult(PoulpeAuthService.java:174)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthService.registerUser(PoulpeAuthService.java:80)
	at org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest.testRegisterUserShouldFailIfInternalServerErrorOccurred(PoulpeAuthServiceTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="1" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testRegisterUserWithCorrectParametersShouldBeSuccessful()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testRegisterUserWithCorrectParametersShouldBeSuccessful" duration-ms="0" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
        <test-method status="PASS" signature="testRegisterUserWithInvalidCredentialsShouldFail()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.service.PoulpeAuthServiceTest@1fe2d13]" name="testRegisterUserWithInvalidCredentialsShouldFail" duration-ms="7" started-at="2017-03-21T19:33:49Z" finished-at="2017-03-21T19:33:49Z">
        </test-method>
      </class>
      <class name="org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="163" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable" duration-ms="21" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException">
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:110)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowNoConnectionExceptionIfPoulpeUnavailable(PoulpeAuthPluginTest.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred" duration-ms="2" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException">
            <message>
              <![CDATA[javax.xml.bind.JAXBException: ]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:113)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.authenticateShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred(PoulpeAuthPluginTest.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.authenticate(PoulpeAuthPlugin.java:110)
	... 35 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="pluginWithIncorrectParametersShouldNotBeConfigured()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="pluginWithIncorrectParametersShouldNotBeConfigured" duration-ms="3" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="pluginWithIncorrectParametersShouldThrowException()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="pluginWithIncorrectParametersShouldThrowException" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException">
            <message>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Url should not be null.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Url should not be null.
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:63)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectParametersShouldThrowException(PoulpeAuthPluginTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Url should not be null.
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.applyConfiguration(PoulpeAuthPlugin.java:168)
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:52)
	... 35 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="pluginWithIncorrectUrlShouldNotBeConfigured()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="pluginWithIncorrectUrlShouldNotBeConfigured" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="pluginWithIncorrectUrlShouldThrowException()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="pluginWithIncorrectUrlShouldThrowException" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException">
            <message>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Incorrect format for Url value.]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Incorrect format for Url value.
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:63)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.pluginWithIncorrectUrlShouldThrowException(PoulpeAuthPluginTest.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: org.jtalks.jcommune.plugin.api.exceptions.PluginConfigurationException: Can't apply configuration: Incorrect format for Url value.
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.applyConfiguration(PoulpeAuthPlugin.java:170)
	at org.jtalks.jcommune.plugin.api.core.StatefullPlugin.configure(StatefullPlugin.java:52)
	... 35 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable" duration-ms="2" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException">
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.NoConnectionException
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:79)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerUser(PoulpeAuthPlugin.java:64)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowNoConnectionExceptionIfPoulpeUnavailable(PoulpeAuthPluginTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
          <exception class="org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException">
            <message>
              <![CDATA[javax.xml.bind.JAXBException: ]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.jtalks.jcommune.plugin.api.exceptions.UnexpectedErrorException: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:82)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerUser(PoulpeAuthPlugin.java:64)
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest.registerUserShouldThrowUnexpectedErrorExceptionIfSomeErrorOccurred(PoulpeAuthPluginTest.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: javax.xml.bind.JAXBException: 
	at org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPlugin.registerOrValidate(PoulpeAuthPlugin.java:79)
	... 36 more
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="testConfigure()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="testConfigure" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="translateLabelWithExistingTranslation()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="translateLabelWithExistingTranslation" duration-ms="3" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="translateLabelWithoutExistingTranslation()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="translateLabelWithoutExistingTranslation" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="userShouldNotBeAuthenticatedIfSomeErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="userShouldNotBeAuthenticatedIfSomeErrorOccurred" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="userShouldNotBeRegisteredIfSomeErrorOccurred()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="userShouldNotBeRegisteredIfSomeErrorOccurred" duration-ms="1" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="userWithCorrectParametersShouldBeAuthenticated()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="userWithCorrectParametersShouldBeAuthenticated" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="setUp()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="setUp" is-config="true" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
        <test-method status="PASS" signature="userWithCorrectParametersShouldBeRegistered()[pri:0, instance:org.jtalks.jcommune.plugin.auth.poulpe.PoulpeAuthPluginTest@161df1f]" name="userWithCorrectParametersShouldBeRegistered" duration-ms="0" started-at="2017-03-21T19:33:47Z" finished-at="2017-03-21T19:33:47Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
